In [1]:
#convex optimization Python library
import cvxpy as cp
import numpy as np

## Exercise 5

In this exercise we have the following Linear program:

<p style="text-align: center;"> minimize $f_0(x_1,x_2)$ </p>

<p style="text-align: center;"> subject to  $\left\{\begin{matrix} 2x_1+x_2 \geq 1
 \\ x_1+3x_2 \geq 1
 \\ x_1 \geq 0,\;\; x_2 \geq 0
\end{matrix}\right.$ ,</p>

which is a particular case of a convex optimization problem. Both the objective and constraint functions are all linear. The program will then apply the library CVXPY to optimize this problem with different objective functions. Both the optimal values and optimal point are printed.

In [2]:
#Optimization variables
x1 = cp.Variable()
x2 = cp.Variable()

In [3]:
#Constraints of the problem (it is the same for all the different objective functions
constraints = [2*x1 + x2 >= 1,
               x1 + 3*x2 >= 1,
               x1 >= 0,
               x2 >= 0]

### Objective function a): $f_0(x_1,x_2) = x_1 + x_2$

In [4]:
#Definition of the objective function and the problem to be solved (in this case, minimization)
obj = cp.Minimize(x1+x2)

In [5]:
#This part connects the constraints with the objective function
prob = cp.Problem(obj, constraints)

#This part executes the optimization
sol = prob.solve()

print('The optimal value is: ',sol)
print()
print('Values for the optimal set:')
print('x1 = ',x1.value)
print('x2 = ',x2.value)

The optimal value is:  0.6000000000007311

Values for the optimal set:
x1 =  0.40000000000049696
x2 =  0.20000000000023407


### Objective function b): $f_0(x_1,x_2) = - (x_1 + x_2)$

In [6]:
#Definition of the objective function and the problem to be solved (in this case, minimization)
obj = cp.Minimize(-x1-x2)

In [7]:
#This part connects the constraints with the objective function
prob = cp.Problem(obj, constraints)

#This part executes the optimization
sol = prob.solve()

print('The optimal value is: ',sol)
print()
print('Values for the optimal set:')
print('x1 = ',x1.value)
print('x2 = ',x2.value)

The optimal value is:  -inf

Values for the optimal set:
x1 =  None
x2 =  None


### Objective function c): $f_0(x_1,x_2) = x_1$

In [8]:
#Definition of the objective function and the problem to be solved (in this case, minimization)
obj = cp.Minimize(x1)

In [9]:
#This part connects the constraints with the objective function
prob = cp.Problem(obj, constraints)

#This part executes the optimization
sol = prob.solve()

print('The optimal value is: ',sol)
print()
print('Values for the optimal set:')
print('x1 = ',x1.value)
print('x2 = ',x2.value)

The optimal value is:  0.0

Values for the optimal set:
x1 =  0.0
x2 =  1.0


# Exercise 6

In this problem, we have a SDP to optimize. A SDP is a convex optimization problem where the objective function is the trace of a matrix times the optimization variable matrix. The optimization variable has to be a positive semidefinite matrix and the constraint functions are all the trace of different matrices times the optimization variable, which is again a linear (therefore convex) function. In this case, the problem we want to solve is the following:

<p style="text-align: center;"> maximize $\text{Tr}(AX)$ </p>

<p style="text-align: center;"> subject to  $\left\{\begin{matrix} \text{Tr}(X) = 1 
 \\ \text{Tr}(BX) = 1
 \\ X \succeq 0
\end{matrix}\right.$ ,</p>

where the notation $X \succeq 0$ means that $X$ is a positive semidefinite matrix. This will, we are going to optimize over a positive semidefinite matrix with unitary trace, like a density matrix describing a quantum state.

In [10]:
#Definition of the matrices appearing in the problem

A = np.matrix([[0, 0, 0, 1],
               [0, 0, 1, 0],
               [0, 1, 0, 0],
               [1, 0, 0, 0]])

B = np.matrix([[1, 0, 0, 0],
                [0, -1, 0, 0],
                [0, 0, -1, 0],
                [0, 0, 0, 1]])

#Definition of the variable of the problem
X = cp.Variable((4,4), symmetric=True)

In [11]:
#Definition of the constraints of the optimization problem
constraints_SDP = [cp.trace(B @ X) == 1,
                   cp.trace(X) == 1,
                   X >> 0]

#Definition of the objective function and the problem to be solved
obj_SDP = cp.Maximize(cp.trace(A@X))

In [12]:
#This part connects the constraints with the objective function
prob = cp.Problem(obj_SDP, constraints_SDP)

#This part executes the optimization
sol = prob.solve()

In [13]:
print('The optimal value is: ')
print(sol)
print('Values for the optimal set:')
print('X = ')
print(X.value)

The optimal value is: 
1.0000000000016853
Values for the optimal set:
X = 
[[ 5.00000000e-01 -2.10498613e-17  5.09391321e-18  5.00000000e-01]
 [-2.10498613e-17  4.26694290e-13  1.50252969e-12 -2.10499908e-17]
 [ 5.09391321e-18  1.50252969e-12  4.26694291e-13  5.09393864e-18]
 [ 5.00000000e-01 -2.10499908e-17  5.09393864e-18  5.00000000e-01]]
